#!/usr/bin/env bash

python3 main.py --k=-0.8 > resultados/resultado_m_0_8.txt
python3 main.py --k=-0.5 > resultados/resultado_m_0_5.txt
python3 main.py --k=0.0 > resultados/resultado_0_0.txt
python3 main.py --k=0.5 > resultados/resultado_0_5.txt
python3 main.py --k=0.8 > resultados/resultado_0_8.txt